apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: R2if2Ol2H0bNyL7OxUYJqs2ZZ0RfzFLwTOpovPDFf2eZlbUsGdKshnVYw9ohPF1
  POSTGRES_PASSWORD: ZKqY+m4JA0s0mMMRTDUb2dHvNNvAT7wR0T13KultdrHTVWv4JW01VRqHLOMNm5
