apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  KAFKA_BROKERS: kafka:9092
  KAFKA_TRANSACTIONS_TOPIC: transactions
  REDIS_MASTER_NAME: mymaster
  REDIS_SENTINELS: redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
  POSTGRES_DB: facade_db
  POSTGRES_USER: facade_user
