apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-1
  template:
    metadata:
      labels:
        app: redis-1
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_REPLICATION_MODE
              value: master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: redis-1
spec:
  selector:
    app: redis-1
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-2
  template:
    metadata:
      labels:
        app: redis-2
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_REPLICATION_MODE
              value: replica
            - name: REDIS_MASTER_HOST
              value: redis-1
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: redis-2
spec:
  selector:
    app: redis-2
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-3
  template:
    metadata:
      labels:
        app: redis-3
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_REPLICATION_MODE
              value: replica
            - name: REDIS_MASTER_HOST
              value: redis-1
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: redis-3
spec:
  selector:
    app: redis-3
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
